version: '3.9'

services:
    db:
        image: postgres
        volumes:
            - pento_db_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres

    elixir:
        build: ./
        ports:
          - 4000:4000
        volumes:
          - /data/src/elixir/phx/pento:/app
          - pento_elixir_root:/root
        depends_on:
          - db
        working_dir: /app
        command: sleep 10d
        
volumes:
  pento_db_data:
  pento_elixir_root:
